/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class DevAddr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DevAddr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DevAddr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCEndpointUtilJNI.delete_DevAddr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setIpv6(OCIPv6Addr value) {
    OCEndpointUtilJNI.DevAddr_ipv6_set(swigCPtr, this, OCIPv6Addr.getCPtr(value), value);
  }

  public OCIPv6Addr getIpv6() {
    long cPtr = OCEndpointUtilJNI.DevAddr_ipv6_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCIPv6Addr(cPtr, false);
  }

  public void setIpv4(OCIPv4Addr value) {
    OCEndpointUtilJNI.DevAddr_ipv4_set(swigCPtr, this, OCIPv4Addr.getCPtr(value), value);
  }

  public OCIPv4Addr getIpv4() {
    long cPtr = OCEndpointUtilJNI.DevAddr_ipv4_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCIPv4Addr(cPtr, false);
  }

  public void setBt(OCLEAddr value) {
    OCEndpointUtilJNI.DevAddr_bt_set(swigCPtr, this, OCLEAddr.getCPtr(value), value);
  }

  public OCLEAddr getBt() {
    long cPtr = OCEndpointUtilJNI.DevAddr_bt_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCLEAddr(cPtr, false);
  }

  public DevAddr() {
    this(OCEndpointUtilJNI.new_DevAddr(), true);
  }

}
