/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public enum oc_content_format_t {
  TEXT_PLAIN(0),
  TEXT_XML(1),
  TEXT_CSV(2),
  TEXT_HTML(3),
  IMAGE_GIF(21),
  IMAGE_JPEG(22),
  IMAGE_PNG(23),
  IMAGE_TIFF(24),
  AUDIO_RAW(25),
  VIDEO_RAW(26),
  APPLICATION_LINK_FORMAT(40),
  APPLICATION_XML(41),
  APPLICATION_OCTET_STREAM(42),
  APPLICATION_RDF_XML(43),
  APPLICATION_SOAP_XML(44),
  APPLICATION_ATOM_XML(45),
  APPLICATION_XMPP_XML(46),
  APPLICATION_EXI(47),
  APPLICATION_FASTINFOSET(48),
  APPLICATION_SOAP_FASTINFOSET(49),
  APPLICATION_JSON(50),
  APPLICATION_X_OBIX_BINARY(51),
  APPLICATION_CBOR(60),
  APPLICATION_VND_OCF_CBOR(10000);

  public final int swigValue() {
    return swigValue;
  }

  public static oc_content_format_t swigToEnum(int swigValue) {
    oc_content_format_t[] swigValues = oc_content_format_t.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (oc_content_format_t swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + oc_content_format_t.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private oc_content_format_t() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private oc_content_format_t(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private oc_content_format_t(oc_content_format_t swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

