/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public enum OCAceSubjectType {
  OC_SUBJECT_UUID(0),
  OC_SUBJECT_ROLE,
  OC_SUBJECT_CONN;

  public final int swigValue() {
    return swigValue;
  }

  public static OCAceSubjectType swigToEnum(int swigValue) {
    OCAceSubjectType[] swigValues = OCAceSubjectType.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (OCAceSubjectType swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + OCAceSubjectType.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private OCAceSubjectType() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private OCAceSubjectType(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private OCAceSubjectType(OCAceSubjectType swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

