/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public enum OCAceWildcard {
  OC_ACE_NO_WC(0),
  OC_ACE_WC_ALL(0x111),
  OC_ACE_WC_ALL_SECURED(0x01),
  OC_ACE_WC_ALL_PUBLIC(0x10);

  public final int swigValue() {
    return swigValue;
  }

  public static OCAceWildcard swigToEnum(int swigValue) {
    OCAceWildcard[] swigValues = OCAceWildcard.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (OCAceWildcard swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + OCAceWildcard.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private OCAceWildcard() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private OCAceWildcard(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private OCAceWildcard(OCAceWildcard swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

