/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCBufferSettings {
  public static int setMtuSize(long mtu_size) {
    return OCBufferSettingsJNI.setMtuSize(mtu_size);
  }

  public static int getMtuSize() {
    return OCBufferSettingsJNI.getMtuSize();
  }

  public static void setMaxAppDataSize(long size) {
    OCBufferSettingsJNI.setMaxAppDataSize(size);
  }

  public static int getMaxAppDataSize() {
    return OCBufferSettingsJNI.getMaxAppDataSize();
  }

  public static int getBlockSize() {
    return OCBufferSettingsJNI.getBlockSize();
  }

}
