/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCClientResponse {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCClientResponse(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCClientResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCMainJNI.delete_OCClientResponse(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPayload(OCRepresentation value) {
    OCMainJNI.OCClientResponse_payload_set(swigCPtr, this, OCRepresentation.getCPtr(value), value);
  }

  public OCRepresentation getPayload() {
    long cPtr = OCMainJNI.OCClientResponse_payload_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCRepresentation(cPtr, false);
  }

  public void set_payload(SWIGTYPE_p_unsigned_char value) {
    OCMainJNI.OCClientResponse__payload_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char get_payload() {
    long cPtr = OCMainJNI.OCClientResponse__payload_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void set_payload_len(long value) {
    OCMainJNI.OCClientResponse__payload_len_set(swigCPtr, this, value);
  }

  public long get_payload_len() {
    return OCMainJNI.OCClientResponse__payload_len_get(swigCPtr, this);
  }

  public void setEndpoint(OCEndpoint value) {
    OCMainJNI.OCClientResponse_endpoint_set(swigCPtr, this, OCEndpoint.getCPtr(value), value);
  }

  public OCEndpoint getEndpoint() {
    long cPtr = OCMainJNI.OCClientResponse_endpoint_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCEndpoint(cPtr, false);
  }

  public void setContent_format(oc_content_format_t value) {
    OCMainJNI.OCClientResponse_content_format_set(swigCPtr, this, value.swigValue());
  }

  public oc_content_format_t getContent_format() {
    return oc_content_format_t.swigToEnum(OCMainJNI.OCClientResponse_content_format_get(swigCPtr, this));
  }

  public void setCode(OCStatus value) {
    OCMainJNI.OCClientResponse_code_set(swigCPtr, this, value.swigValue());
  }

  public OCStatus getCode() {
    return OCStatus.swigToEnum(OCMainJNI.OCClientResponse_code_get(swigCPtr, this));
  }

  public void setObserve_option(int value) {
    OCMainJNI.OCClientResponse_observe_option_set(swigCPtr, this, value);
  }

  public int getObserve_option() {
    return OCMainJNI.OCClientResponse_observe_option_get(swigCPtr, this);
  }

  public OCClientResponse() {
    this(OCMainJNI.new_OCClientResponse(), true);
  }

}
