/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCClockJNI {
  public final static native int CLOCKS_PER_SEC_get();
  public final static native int OC_CLOCK_CONF_TICKS_PER_SECOND_get();
  public final static native int OC_DTLS_INACTIVITY_TIMEOUT_get();
  public final static native int SELECT_TIMEOUT_SEC_get();

  static {
    try {
        System.loadLibrary("iotivity-lite-jni");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native int OC_CLOCK_SECOND_get();
  public final static native void clockInit();
  public final static native long clockTime();
  public final static native long clockSeconds();
  public final static native void clockWait(long jarg1);
}
