/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public interface OCClockConstants {
  public final static int CLOCKS_PER_SEC = OCClockJNI.CLOCKS_PER_SEC_get();
  public final static int OC_CLOCK_CONF_TICKS_PER_SECOND = OCClockJNI.OC_CLOCK_CONF_TICKS_PER_SECOND_get();
  public final static int OC_DTLS_INACTIVITY_TIMEOUT = OCClockJNI.OC_DTLS_INACTIVITY_TIMEOUT_get();
  public final static int SELECT_TIMEOUT_SEC = OCClockJNI.SELECT_TIMEOUT_SEC_get();
  public final static int OC_CLOCK_SECOND = OCClockJNI.OC_CLOCK_SECOND_get();
}
