/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCCloudJNI {

  static {
    try {
        System.loadLibrary("iotivity-lite-jni");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native long getContext(long jarg1);
  public final static native int managerStart(long jarg1, OCCloudContext jarg1_, OCCloudHandler jarg2);
  public final static native int managerStop(long jarg1, OCCloudContext jarg1_);
  public final static native int registerCloud(long jarg1, OCCloudContext jarg1_, OCCloudHandler jarg2);
  public final static native int login(long jarg1, OCCloudContext jarg1_, OCCloudHandler jarg2);
  public final static native int logout(long jarg1, OCCloudContext jarg1_, OCCloudHandler jarg2);
  public final static native int deregisterCloud(long jarg1, OCCloudContext jarg1_, OCCloudHandler jarg2);
  public final static native int refreshToken(long jarg1, OCCloudContext jarg1_, OCCloudHandler jarg2);
  public final static native int getTokenExpiry(long jarg1, OCCloudContext jarg1_);
  public final static native int addResource(long jarg1, OCResource jarg1_);
  public final static native void deleteResource(long jarg1, OCResource jarg1_);
  public final static native int publishResources(long jarg1);
  public final static native int discoverResources(long jarg1, OCCloudContext jarg1_, OCDiscoveryAllHandler jarg2);
  public final static native int provisionConfResource(long jarg1, OCCloudContext jarg1_, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native void OCCloudStore_ci_server_set(long jarg1, OCCloudStore jarg1_, String jarg2);
  public final static native String OCCloudStore_ci_server_get(long jarg1, OCCloudStore jarg1_);
  public final static native void OCCloudStore_auth_provider_set(long jarg1, OCCloudStore jarg1_, String jarg2);
  public final static native String OCCloudStore_auth_provider_get(long jarg1, OCCloudStore jarg1_);
  public final static native void OCCloudStore_uid_set(long jarg1, OCCloudStore jarg1_, String jarg2);
  public final static native String OCCloudStore_uid_get(long jarg1, OCCloudStore jarg1_);
  public final static native void OCCloudStore_access_token_set(long jarg1, OCCloudStore jarg1_, String jarg2);
  public final static native String OCCloudStore_access_token_get(long jarg1, OCCloudStore jarg1_);
  public final static native void OCCloudStore_refresh_token_set(long jarg1, OCCloudStore jarg1_, String jarg2);
  public final static native String OCCloudStore_refresh_token_get(long jarg1, OCCloudStore jarg1_);
  public final static native void OCCloudStore_sid_set(long jarg1, OCCloudStore jarg1_, String jarg2);
  public final static native String OCCloudStore_sid_get(long jarg1, OCCloudStore jarg1_);
  public final static native void OCCloudStore_status_set(long jarg1, OCCloudStore jarg1_, short jarg2);
  public final static native short OCCloudStore_status_get(long jarg1, OCCloudStore jarg1_);
  public final static native void OCCloudStore_cps_set(long jarg1, OCCloudStore jarg1_, int jarg2);
  public final static native int OCCloudStore_cps_get(long jarg1, OCCloudStore jarg1_);
  public final static native void OCCloudStore_device_set(long jarg1, OCCloudStore jarg1_, long jarg2);
  public final static native long OCCloudStore_device_get(long jarg1, OCCloudStore jarg1_);
  public final static native long new_OCCloudStore();
  public final static native void delete_OCCloudStore(long jarg1);
  public final static native void OCCloudContext_next_set(long jarg1, OCCloudContext jarg1_, long jarg2, OCCloudContext jarg2_);
  public final static native long OCCloudContext_next_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_device_set(long jarg1, OCCloudContext jarg1_, long jarg2);
  public final static native long OCCloudContext_device_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_store_set(long jarg1, OCCloudContext jarg1_, long jarg2, OCCloudStore jarg2_);
  public final static native long OCCloudContext_store_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_cloudEndpointState_set(long jarg1, OCCloudContext jarg1_, int jarg2);
  public final static native int OCCloudContext_cloudEndpointState_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_cloudEndpoint_set(long jarg1, OCCloudContext jarg1_, long jarg2, OCEndpoint jarg2_);
  public final static native long OCCloudContext_cloudEndpoint_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_retryCount_set(long jarg1, OCCloudContext jarg1_, short jarg2);
  public final static native short OCCloudContext_retryCount_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_retryRefreshTokenCount_set(long jarg1, OCCloudContext jarg1_, short jarg2);
  public final static native short OCCloudContext_retryRefreshTokenCount_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_lastError_set(long jarg1, OCCloudContext jarg1_, int jarg2);
  public final static native int OCCloudContext_lastError_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_expiresIn_set(long jarg1, OCCloudContext jarg1_, int jarg2);
  public final static native int OCCloudContext_expiresIn_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_rdPublishResources_set(long jarg1, OCCloudContext jarg1_, long jarg2, OCLink jarg2_);
  public final static native long OCCloudContext_rdPublishResources_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_rdPublishedResources_set(long jarg1, OCCloudContext jarg1_, long jarg2, OCLink jarg2_);
  public final static native long OCCloudContext_rdPublishedResources_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_rdDeleteResources_set(long jarg1, OCCloudContext jarg1_, long jarg2, OCLink jarg2_);
  public final static native long OCCloudContext_rdDeleteResources_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_rdDeleteAll_set(long jarg1, OCCloudContext jarg1_, boolean jarg2);
  public final static native boolean OCCloudContext_rdDeleteAll_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_cloudConf_set(long jarg1, OCCloudContext jarg1_, long jarg2, OCResource jarg2_);
  public final static native long OCCloudContext_cloudConf_get(long jarg1, OCCloudContext jarg1_);
  public final static native void OCCloudContext_cloudManager_set(long jarg1, OCCloudContext jarg1_, boolean jarg2);
  public final static native boolean OCCloudContext_cloudManager_get(long jarg1, OCCloudContext jarg1_);
  public final static native long new_OCCloudContext();
  public final static native void delete_OCCloudContext(long jarg1);
}
