/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCCloudStore {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCCloudStore(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCCloudStore obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCCloudJNI.delete_OCCloudStore(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCi_server(String value) {
    OCCloudJNI.OCCloudStore_ci_server_set(swigCPtr, this, value);
  }

  public String getCi_server() {
    return OCCloudJNI.OCCloudStore_ci_server_get(swigCPtr, this);
  }

  public void setAuth_provider(String value) {
    OCCloudJNI.OCCloudStore_auth_provider_set(swigCPtr, this, value);
  }

  public String getAuth_provider() {
    return OCCloudJNI.OCCloudStore_auth_provider_get(swigCPtr, this);
  }

  public void setUid(String value) {
    OCCloudJNI.OCCloudStore_uid_set(swigCPtr, this, value);
  }

  public String getUid() {
    return OCCloudJNI.OCCloudStore_uid_get(swigCPtr, this);
  }

  public void setAccess_token(String value) {
    OCCloudJNI.OCCloudStore_access_token_set(swigCPtr, this, value);
  }

  public String getAccess_token() {
    return OCCloudJNI.OCCloudStore_access_token_get(swigCPtr, this);
  }

  public void setRefresh_token(String value) {
    OCCloudJNI.OCCloudStore_refresh_token_set(swigCPtr, this, value);
  }

  public String getRefresh_token() {
    return OCCloudJNI.OCCloudStore_refresh_token_get(swigCPtr, this);
  }

  public void setSid(String value) {
    OCCloudJNI.OCCloudStore_sid_set(swigCPtr, this, value);
  }

  public String getSid() {
    return OCCloudJNI.OCCloudStore_sid_get(swigCPtr, this);
  }

  public void setStatus(short value) {
    OCCloudJNI.OCCloudStore_status_set(swigCPtr, this, value);
  }

  public short getStatus() {
    return OCCloudJNI.OCCloudStore_status_get(swigCPtr, this);
  }

  public void setCps(OCCloudPrivisoningStatus value) {
    OCCloudJNI.OCCloudStore_cps_set(swigCPtr, this, value.swigValue());
  }

  public OCCloudPrivisoningStatus getCps() {
    return OCCloudPrivisoningStatus.swigToEnum(OCCloudJNI.OCCloudStore_cps_get(swigCPtr, this));
  }

  public void setDevice(long value) {
    OCCloudJNI.OCCloudStore_device_set(swigCPtr, this, value);
  }

  public long getDevice() {
    return OCCloudJNI.OCCloudStore_device_get(swigCPtr, this);
  }

  public OCCloudStore() {
    this(OCCloudJNI.new_OCCloudStore(), true);
  }

}
