/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCCoreResJNI {

  static {
    try {
        System.loadLibrary("iotivity-lite-jni");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native long initPlatform__SWIG_0(String jarg1);
  public final static native long initPlatform__SWIG_1(String jarg1, OCCoreInitPlatformHandler jarg2);
  public final static native long OCCoreAddNewDevice__SWIG_0(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native long OCCoreAddNewDevice__SWIG_1(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5, OCCoreAddDeviceHandler jarg6);
  public final static native void OCPlatformInfo_pi_set(long jarg1, OCPlatformInfo jarg1_, long jarg2, OCUuid jarg2_);
  public final static native long OCPlatformInfo_pi_get(long jarg1, OCPlatformInfo jarg1_);
  public final static native void OCPlatformInfo_mfg_name_set(long jarg1, OCPlatformInfo jarg1_, String jarg2);
  public final static native String OCPlatformInfo_mfg_name_get(long jarg1, OCPlatformInfo jarg1_);
  public final static native long new_OCPlatformInfo();
  public final static native void delete_OCPlatformInfo(long jarg1);
  public final static native void OCDeviceInfo_di_set(long jarg1, OCDeviceInfo jarg1_, long jarg2, OCUuid jarg2_);
  public final static native long OCDeviceInfo_di_get(long jarg1, OCDeviceInfo jarg1_);
  public final static native void OCDeviceInfo_piid_set(long jarg1, OCDeviceInfo jarg1_, long jarg2, OCUuid jarg2_);
  public final static native long OCDeviceInfo_piid_get(long jarg1, OCDeviceInfo jarg1_);
  public final static native void OCDeviceInfo_name_set(long jarg1, OCDeviceInfo jarg1_, String jarg2);
  public final static native String OCDeviceInfo_name_get(long jarg1, OCDeviceInfo jarg1_);
  public final static native void OCDeviceInfo_icv_set(long jarg1, OCDeviceInfo jarg1_, String jarg2);
  public final static native String OCDeviceInfo_icv_get(long jarg1, OCDeviceInfo jarg1_);
  public final static native void OCDeviceInfo_dmv_set(long jarg1, OCDeviceInfo jarg1_, String jarg2);
  public final static native String OCDeviceInfo_dmv_get(long jarg1, OCDeviceInfo jarg1_);
  public final static native long new_OCDeviceInfo();
  public final static native void delete_OCDeviceInfo(long jarg1);
  public final static native void init();
  public final static native void shutdown();
  public final static native long getNumDevices();
  public final static native long getDeviceId(long jarg1);
  public final static native long getDeviceInfo(long jarg1);
  public final static native long getPlatformInfo();
  public final static native void encodeInterfacesMask(long jarg1, CborEncoder jarg1_, int jarg2);
  public final static native long getResourceByIndex(int jarg1, long jarg2);
  public final static native long getResourceByUri(String jarg1, long jarg2);
  public final static native boolean filterResourceByRt(long jarg1, OCResource jarg1_, long jarg2, OCRequest jarg2_);
  public final static native boolean isDCR(long jarg1, OCResource jarg1_, long jarg2);
  public final static native boolean oc_core_is_SVR(long jarg1, OCResource jarg1_, long jarg2);
  public final static native boolean oc_core_is_vertical_resource(long jarg1, OCResource jarg1_, long jarg2);
  public final static native void oc_core_set_latency(int jarg1);
  public final static native int oc_core_get_latency();
}
