/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCCredUtil {
  public static String readCredUsage(OCCredUsage credusage) {
    return OCCredUtilJNI.readCredUsage(credusage.swigValue());
  }

  public static String readEncoding(OCEncoding encoding) {
    return OCCredUtilJNI.readEncoding(encoding.swigValue());
  }

  public static OCCredUsage parseCredUsage(String credusageString) {
    return OCCredUsage.swigToEnum(OCCredUtilJNI.parseCredUsage(credusageString));
  }

  public static OCEncoding parseEncoding(String encodingString) {
    return OCEncoding.swigToEnum(OCCredUtilJNI.parseEncoding(encodingString));
  }

  public static String credTypeString(OCCredType credType) {
    return OCCredUtilJNI.credTypeString(credType.swigValue());
  }

}
