/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCCredUtilJNI {

  static {
    try {
        System.loadLibrary("iotivity-lite-jni");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native String readCredUsage(int jarg1);
  public final static native String readEncoding(int jarg1);
  public final static native int parseCredUsage(String jarg1);
  public final static native int parseEncoding(String jarg1);
  public final static native String credTypeString(int jarg1);
  public final static native void OCCredData_data_set(long jarg1, OCCredData jarg1_, String jarg2);
  public final static native String OCCredData_data_get(long jarg1, OCCredData jarg1_);
  public final static native void OCCredData_encoding_set(long jarg1, OCCredData jarg1_, int jarg2);
  public final static native int OCCredData_encoding_get(long jarg1, OCCredData jarg1_);
  public final static native long new_OCCredData();
  public final static native void delete_OCCredData(long jarg1);
  public final static native void OCCred_next_set(long jarg1, OCCred jarg1_, long jarg2, OCCred jarg2_);
  public final static native long OCCred_next_get(long jarg1, OCCred jarg1_);
  public final static native void OCCred_privateData_set(long jarg1, OCCred jarg1_, long jarg2, OCCredData jarg2_);
  public final static native long OCCred_privateData_get(long jarg1, OCCred jarg1_);
  public final static native void OCCred_credId_set(long jarg1, OCCred jarg1_, int jarg2);
  public final static native int OCCred_credId_get(long jarg1, OCCred jarg1_);
  public final static native void OCCred_credType_set(long jarg1, OCCred jarg1_, int jarg2);
  public final static native int OCCred_credType_get(long jarg1, OCCred jarg1_);
  public final static native void OCCred_subjectUuid_set(long jarg1, OCCred jarg1_, long jarg2, OCUuid jarg2_);
  public final static native long OCCred_subjectUuid_get(long jarg1, OCCred jarg1_);
  public final static native void OCCred_ownerCred_set(long jarg1, OCCred jarg1_, boolean jarg2);
  public final static native boolean OCCred_ownerCred_get(long jarg1, OCCred jarg1_);
  public final static native String OCCred_getRole(long jarg1, OCCred jarg1_);
  public final static native String OCCred_getAuthority(long jarg1, OCCred jarg1_);
  public final static native long OCCred_getPublicData(long jarg1, OCCred jarg1_);
  public final static native int OCCred_getCredUsage(long jarg1, OCCred jarg1_);
  public final static native long OCCred_getChain(long jarg1, OCCred jarg1_);
  public final static native long OCCred_getChild(long jarg1, OCCred jarg1_);
  public final static native long new_OCCred();
  public final static native void delete_OCCred(long jarg1);
  public final static native void OCCreds_rowneruuid_set(long jarg1, OCCreds jarg1_, long jarg2, OCUuid jarg2_);
  public final static native long OCCreds_rowneruuid_get(long jarg1, OCCreds jarg1_);
  public final static native long OCCreds_getCredsListHead(long jarg1, OCCreds jarg1_);
  public final static native void delete_OCCreds(long jarg1);
}
