/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public enum OCCredUsage {
  OC_CREDUSAGE_NULL(0),
  OC_CREDUSAGE_TRUSTCA(1 << 1),
  OC_CREDUSAGE_IDENTITY_CERT(1 << 2),
  OC_CREDUSAGE_ROLE_CERT(1 << 3),
  OC_CREDUSAGE_MFG_TRUSTCA(1 << 4),
  OC_CREDUSAGE_MFG_CERT(1 << 5);

  public final int swigValue() {
    return swigValue;
  }

  public static OCCredUsage swigToEnum(int swigValue) {
    OCCredUsage[] swigValues = OCCredUsage.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (OCCredUsage swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + OCCredUsage.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private OCCredUsage() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private OCCredUsage(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private OCCredUsage(OCCredUsage swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

