/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCCred {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCCred(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCCred obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCCredUtilJNI.delete_OCCred(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNext(OCCred value) {
    OCCredUtilJNI.OCCred_next_set(swigCPtr, this, OCCred.getCPtr(value), value);
  }

  public OCCred getNext() {
    long cPtr = OCCredUtilJNI.OCCred_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCCred(cPtr, false);
  }

  public void setPrivateData(OCCredData value) {
    OCCredUtilJNI.OCCred_privateData_set(swigCPtr, this, OCCredData.getCPtr(value), value);
  }

  public OCCredData getPrivateData() {
    long cPtr = OCCredUtilJNI.OCCred_privateData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCCredData(cPtr, false);
  }

  public void setCredId(int value) {
    OCCredUtilJNI.OCCred_credId_set(swigCPtr, this, value);
  }

  public int getCredId() {
    return OCCredUtilJNI.OCCred_credId_get(swigCPtr, this);
  }

  public void setCredType(OCCredType value) {
    OCCredUtilJNI.OCCred_credType_set(swigCPtr, this, value.swigValue());
  }

  public OCCredType getCredType() {
    return OCCredType.swigToEnum(OCCredUtilJNI.OCCred_credType_get(swigCPtr, this));
  }

  public void setSubjectUuid(OCUuid value) {
    OCCredUtilJNI.OCCred_subjectUuid_set(swigCPtr, this, OCUuid.getCPtr(value), value);
  }

  public OCUuid getSubjectUuid() {
    long cPtr = OCCredUtilJNI.OCCred_subjectUuid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCUuid(cPtr, false);
  }

  public void setOwnerCred(boolean value) {
    OCCredUtilJNI.OCCred_ownerCred_set(swigCPtr, this, value);
  }

  public boolean getOwnerCred() {
    return OCCredUtilJNI.OCCred_ownerCred_get(swigCPtr, this);
  }

  public String getRole() {
    return OCCredUtilJNI.OCCred_getRole(swigCPtr, this);
  }

  public String getAuthority() {
    return OCCredUtilJNI.OCCred_getAuthority(swigCPtr, this);
  }

  public OCCredData getPublicData() {
    long cPtr = OCCredUtilJNI.OCCred_getPublicData(swigCPtr, this);
    return (cPtr == 0) ? null : new OCCredData(cPtr, false);
  }

  public OCCredUsage getCredUsage() {
    return OCCredUsage.swigToEnum(OCCredUtilJNI.OCCred_getCredUsage(swigCPtr, this));
  }

  public OCCred getChain() {
    long cPtr = OCCredUtilJNI.OCCred_getChain(swigCPtr, this);
    return (cPtr == 0) ? null : new OCCred(cPtr, false);
  }

  public OCCred getChild() {
    long cPtr = OCCredUtilJNI.OCCred_getChild(swigCPtr, this);
    return (cPtr == 0) ? null : new OCCred(cPtr, false);
  }

  public OCCred() {
    this(OCCredUtilJNI.new_OCCred(), true);
  }

}
