/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCDeviceInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCDeviceInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCDeviceInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCCoreResJNI.delete_OCDeviceInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDi(OCUuid value) {
    OCCoreResJNI.OCDeviceInfo_di_set(swigCPtr, this, OCUuid.getCPtr(value), value);
  }

  public OCUuid getDi() {
    long cPtr = OCCoreResJNI.OCDeviceInfo_di_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCUuid(cPtr, false);
  }

  public void setPiid(OCUuid value) {
    OCCoreResJNI.OCDeviceInfo_piid_set(swigCPtr, this, OCUuid.getCPtr(value), value);
  }

  public OCUuid getPiid() {
    long cPtr = OCCoreResJNI.OCDeviceInfo_piid_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCUuid(cPtr, false);
  }

  public void setName(String value) {
    OCCoreResJNI.OCDeviceInfo_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return OCCoreResJNI.OCDeviceInfo_name_get(swigCPtr, this);
  }

  public void setIcv(String value) {
    OCCoreResJNI.OCDeviceInfo_icv_set(swigCPtr, this, value);
  }

  public String getIcv() {
    return OCCoreResJNI.OCDeviceInfo_icv_get(swigCPtr, this);
  }

  public void setDmv(String value) {
    OCCoreResJNI.OCDeviceInfo_dmv_set(swigCPtr, this, value);
  }

  public String getDmv() {
    return OCCoreResJNI.OCDeviceInfo_dmv_get(swigCPtr, this);
  }

  public OCDeviceInfo() {
    this(OCCoreResJNI.new_OCDeviceInfo(), true);
  }

}
