/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCEndpointUtil {
  public static void freeEndpoint(OCEndpoint endpoint) {
    OCEndpointUtilJNI.freeEndpoint(OCEndpoint.getCPtr(endpoint), endpoint);
  }

  public static String toString(OCEndpoint endpoint) {
    return OCEndpointUtilJNI.toString(OCEndpoint.getCPtr(endpoint), endpoint);
  }

  public static OCEndpoint stringToEndpoint(String endpoint_str, String[] uri) throws OCEndpointParseException {
    long cPtr = OCEndpointUtilJNI.stringToEndpoint__SWIG_0(endpoint_str, uri);
    return (cPtr == 0) ? null : new OCEndpoint(cPtr, true);
  }

  public static OCEndpoint stringToEndpoint(String endpoint_str) throws OCEndpointParseException {
    long cPtr = OCEndpointUtilJNI.stringToEndpoint__SWIG_1(endpoint_str);
    return (cPtr == 0) ? null : new OCEndpoint(cPtr, true);
  }

  public static String endpointStringParsePath(String endpoint_str) {
    return OCEndpointUtilJNI.endpointStringParsePath(endpoint_str);
  }

  public static OCEndpoint copy(OCEndpoint source) {
    long cPtr = OCEndpointUtilJNI.copy(OCEndpoint.getCPtr(source), source);
    return (cPtr == 0) ? null : new OCEndpoint(cPtr, true);
  }

  public static OCEndpoint listCopy(OCEndpoint source) {
    long cPtr = OCEndpointUtilJNI.listCopy(OCEndpoint.getCPtr(source), source);
    return (cPtr == 0) ? null : new OCEndpoint(cPtr, true);
  }

  public static OCEndpoint newEndpoint() {
    long cPtr = OCEndpointUtilJNI.newEndpoint();
    return (cPtr == 0) ? null : new OCEndpoint(cPtr, false);
  }

  public static void setDi(OCEndpoint endpoint, OCUuid di) {
    OCEndpointUtilJNI.setDi(OCEndpoint.getCPtr(endpoint), endpoint, OCUuid.getCPtr(di), di);
  }

  public static int ipv6EndpointIsLinkLocal(OCEndpoint endpoint) {
    return OCEndpointUtilJNI.ipv6EndpointIsLinkLocal(OCEndpoint.getCPtr(endpoint), endpoint);
  }

  public static int compare(OCEndpoint ep1, OCEndpoint ep2) {
    return OCEndpointUtilJNI.compare(OCEndpoint.getCPtr(ep1), ep1, OCEndpoint.getCPtr(ep2), ep2);
  }

  public static int compareAddress(OCEndpoint ep1, OCEndpoint ep2) {
    return OCEndpointUtilJNI.compareAddress(OCEndpoint.getCPtr(ep1), ep1, OCEndpoint.getCPtr(ep2), ep2);
  }

  public static void setLocalAddress(OCEndpoint ep, int interface_index) {
    OCEndpointUtilJNI.setLocalAddress(OCEndpoint.getCPtr(ep), ep, interface_index);
  }

}
