/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCEnumUtil {
  public static String enumToString(OCEnum val) {
    return OCEnumUtilJNI.enumToString(val.swigValue());
  }

  public static String positionDescriptionToString(OCPositionDescription pos) {
    return OCEnumUtilJNI.positionDescriptionToString(pos.swigValue());
  }

}
