/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public final class OCFVersion {
  public final static OCFVersion OCF_VER_1_0_0 = new OCFVersion("OCF_VER_1_0_0", OCEndpointUtilJNI.OCF_VER_1_0_0_get());
  public final static OCFVersion OIC_VER_1_1_0 = new OCFVersion("OIC_VER_1_1_0", OCEndpointUtilJNI.OIC_VER_1_1_0_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OCFVersion swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OCFVersion.class + " with value " + swigValue);
  }

  private OCFVersion(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OCFVersion(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OCFVersion(String swigName, OCFVersion swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OCFVersion[] swigValues = { OCF_VER_1_0_0, OIC_VER_1_1_0 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

