/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCLEAddr {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCLEAddr(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCLEAddr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCEndpointUtilJNI.delete_OCLEAddr(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType(short value) {
    OCEndpointUtilJNI.OCLEAddr_type_set(swigCPtr, this, value);
  }

  public short getType() {
    return OCEndpointUtilJNI.OCLEAddr_type_get(swigCPtr, this);
  }

  public void setAddress(short[] value) {
    OCEndpointUtilJNI.OCLEAddr_address_set(swigCPtr, this, value);
  }

  public short[] getAddress() {
    return OCEndpointUtilJNI.OCLEAddr_address_get(swigCPtr, this);
  }

  public OCLEAddr() {
    this(OCEndpointUtilJNI.new_OCLEAddr(), true);
  }

}
