/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;
import java.util.List;
public class OCMainJNI {

  static {
    try {
        System.loadLibrary("iotivity-lite-jni");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native void OCSeparateResponse_active_set(long jarg1, OCSeparateResponse jarg1_, int jarg2);
  public final static native int OCSeparateResponse_active_get(long jarg1, OCSeparateResponse jarg1_);
  public final static native void delete_OCSeparateResponse(long jarg1);
  public final static native void OCResponseBuffer_responseLength_set(long jarg1, OCResponseBuffer jarg1_, long jarg2);
  public final static native long OCResponseBuffer_responseLength_get(long jarg1, OCResponseBuffer jarg1_);
  public final static native void OCResponseBuffer_code_set(long jarg1, OCResponseBuffer jarg1_, int jarg2);
  public final static native int OCResponseBuffer_code_get(long jarg1, OCResponseBuffer jarg1_);
  public final static native long new_OCResponseBuffer();
  public final static native void delete_OCResponseBuffer(long jarg1);
  public final static native void OCResponse_separateResponse_set(long jarg1, OCResponse jarg1_, long jarg2, OCSeparateResponse jarg2_);
  public final static native long OCResponse_separateResponse_get(long jarg1, OCResponse jarg1_);
  public final static native void OCResponse_responseBuffer_set(long jarg1, OCResponse jarg1_, long jarg2, OCResponseBuffer jarg2_);
  public final static native long OCResponse_responseBuffer_get(long jarg1, OCResponse jarg1_);
  public final static native long new_OCResponse();
  public final static native void delete_OCResponse(long jarg1);
  public final static native void OCRequest_origin_set(long jarg1, OCRequest jarg1_, long jarg2, OCEndpoint jarg2_);
  public final static native long OCRequest_origin_get(long jarg1, OCRequest jarg1_);
  public final static native void OCRequest_resource_set(long jarg1, OCRequest jarg1_, long jarg2, OCResource jarg2_);
  public final static native long OCRequest_resource_get(long jarg1, OCRequest jarg1_);
  public final static native String OCRequest_query_get(long jarg1, OCRequest jarg1_);
  public final static native void OCRequest_queryLen_set(long jarg1, OCRequest jarg1_, long jarg2);
  public final static native long OCRequest_queryLen_get(long jarg1, OCRequest jarg1_);
  public final static native void OCRequest_requestPayload_set(long jarg1, OCRequest jarg1_, long jarg2, OCRepresentation jarg2_);
  public final static native long OCRequest_requestPayload_get(long jarg1, OCRequest jarg1_);
  public final static native void OCRequest__payload_set(long jarg1, OCRequest jarg1_, long jarg2);
  public final static native long OCRequest__payload_get(long jarg1, OCRequest jarg1_);
  public final static native void OCRequest__payload_len_set(long jarg1, OCRequest jarg1_, long jarg2);
  public final static native long OCRequest__payload_len_get(long jarg1, OCRequest jarg1_);
  public final static native void OCRequest_content_format_set(long jarg1, OCRequest jarg1_, int jarg2);
  public final static native int OCRequest_content_format_get(long jarg1, OCRequest jarg1_);
  public final static native void OCRequest_response_set(long jarg1, OCRequest jarg1_, long jarg2, OCResponse jarg2_);
  public final static native long OCRequest_response_get(long jarg1, OCRequest jarg1_);
  public final static native long new_OCRequest();
  public final static native void delete_OCRequest(long jarg1);
  public final static native long OCResource_next_get(long jarg1, OCResource jarg1_);
  public final static native long OCResource_device_get(long jarg1, OCResource jarg1_);
  public final static native String OCResource_name_get(long jarg1, OCResource jarg1_);
  public final static native String OCResource_uri_get(long jarg1, OCResource jarg1_);
  public final static native String[] OCResource_types_get(long jarg1, OCResource jarg1_);
  public final static native int OCResource_interfaces_get(long jarg1, OCResource jarg1_);
  public final static native int OCResource_defaultInterface_get(long jarg1, OCResource jarg1_);
  public final static native int OCResource_properties_get(long jarg1, OCResource jarg1_);
  public final static native double[] OCResource_tagPositionRelative_get(long jarg1, OCResource jarg1_);
  public final static native int OCResource_tagPositionDescription_get(long jarg1, OCResource jarg1_);
  public final static native int OCResource_tagFunctionDescription_get(long jarg1, OCResource jarg1_);
  public final static native short OCResource_numObservers_get(long jarg1, OCResource jarg1_);
  public final static native int OCResource_observePeriodSeconds_get(long jarg1, OCResource jarg1_);
  public final static native long new_OCResource();
  public final static native void delete_OCResource(long jarg1);
  public final static native boolean oc_ri_is_app_resource_valid(long jarg1, OCResource jarg1_);

  static {
    try {
        System.loadLibrary("iotivity-lite-jni");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native int mainInit(OCMainInitHandler jarg1);
  public final static native void mainShutdown();
  public final static native void setFactoryPresetsHandler(OCFactoryPresetsHandler jarg1);
  public final static native int addDevice__SWIG_0(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5);
  public final static native int addDevice__SWIG_1(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5, OCAddDeviceHandler jarg6);
  public final static native int initPlatform__SWIG_0(String jarg1);
  public final static native int initPlatform__SWIG_1(String jarg1, OCInitPlatformHandler jarg2);
  public final static native void setRandomPinHandler(OCRandomPinHandler jarg1);
  public final static native void reset();
  public final static native void resetDevice(long jarg1);
  public final static native void addOwnershipStatusHandler(OCOwnershipStatusHandler jarg1);
  public final static native void removeOwnershipStatusHandler(Object jarg1);
  public final static native void resourceMakePublic(long jarg1, OCResource jarg1_);
  public final static native void resourceSetRequestHandler(long jarg1, OCResource jarg1_, int jarg2, OCRequestHandler jarg3);
  public final static native void resourceSetPropertiesHandlers(long jarg1, OCResource jarg1_, OCGetPropertiesHandler jarg2, OCSetPropertiesHandler jarg4);
  public final static native boolean deleteResource(long jarg1, OCResource jarg1_);
  public final static native List<OCQueryValue> getQueryValues(long jarg1, OCRequest jarg1_);
  public final static native boolean doSiteLocalIPv6Discovery(String jarg1, OCDiscoveryHandler jarg2);
  public final static native boolean doSiteLocalIPv6DiscoveryAll(OCDiscoveryAllHandler jarg1);
  public final static native boolean doRealmLocalIPv6Discovery(String jarg1, OCDiscoveryHandler jarg2);
  public final static native boolean doRealmLocalIPv6DiscoveryAll(OCDiscoveryAllHandler jarg1);
  public final static native boolean doIPDiscovery(String jarg1, OCDiscoveryHandler jarg2);
  public final static native boolean doIPDiscoveryAll(OCDiscoveryAllHandler jarg1);
  public final static native boolean doIPDiscoveryAtEndpoint(String jarg1, OCDiscoveryHandler jarg2, long jarg4, OCEndpoint jarg4_);
  public final static native boolean doIPDiscoveryAllAtEndpoint(OCDiscoveryAllHandler jarg1, long jarg3, OCEndpoint jarg3_);
  public final static native boolean doGet(String jarg1, long jarg2, OCEndpoint jarg2_, String jarg3, OCResponseHandler jarg4, int jarg6);
  public final static native boolean doDelete(String jarg1, long jarg2, OCEndpoint jarg2_, String jarg3, OCResponseHandler jarg4, int jarg6);
  public final static native boolean initPut(String jarg1, long jarg2, OCEndpoint jarg2_, String jarg3, OCResponseHandler jarg4, int jarg6);
  public final static native boolean doPut();
  public final static native boolean initPost(String jarg1, long jarg2, OCEndpoint jarg2_, String jarg3, OCResponseHandler jarg4, int jarg6);
  public final static native boolean doPost();
  public final static native boolean doObserve(String jarg1, long jarg2, OCEndpoint jarg2_, String jarg3, OCResponseHandler jarg4, int jarg6);
  public final static native boolean stopObserve(String jarg1, long jarg2, OCEndpoint jarg2_);
  public final static native boolean doRealmLocalIPv6Multicast(String jarg1, String jarg2, OCResponseHandler jarg3);
  public final static native boolean doSiteLocalIPv6Multicast(String jarg1, String jarg2, OCResponseHandler jarg3);
  public final static native boolean doIPMulticast(String jarg1, String jarg2, OCResponseHandler jarg3);
  public final static native void stopMulticast(long jarg1, OCClientResponse jarg1_);
  public final static native void freeServerEndpoints(long jarg1, OCEndpoint jarg1_);
  public final static native long getAllRoles();
  public final static native boolean assertRole(String jarg1, String jarg2, long jarg3, OCEndpoint jarg3_, OCResponseHandler jarg4);
  public final static native void autoAssertRoles(boolean jarg1);
  public final static native void assertAllRoles(long jarg1, OCEndpoint jarg1_, OCResponseHandler jarg2);
  public final static native boolean sendPing(boolean jarg1, long jarg2, OCEndpoint jarg2_, int jarg3, OCResponseHandler jarg4);
  public final static native void setDelayedHandler(OCTriggerHandler jarg1, int jarg3);
  public final static native void removeDelayedHandler(OCTriggerHandler jarg1);
  public final static native boolean getConResAnnounced();
  public final static native void setConResAnnounced(boolean jarg1);
  public final static native boolean isOwnedDevice(long jarg1);
  public final static native long newResource(String jarg1, String jarg2, short jarg3, long jarg4);
  public final static native void resourceBindResourceInterface(long jarg1, OCResource jarg1_, int jarg2);
  public final static native void resourceSetDefaultInterface(long jarg1, OCResource jarg1_, int jarg2);
  public final static native void resourceBindResourceType(long jarg1, OCResource jarg1_, String jarg2);
  public final static native void deviceBindResourceType(long jarg1, String jarg2);
  public final static native void resourceTagPositionDescription(long jarg1, OCResource jarg1_, int jarg2);
  public final static native void resourceTagPositionRelative(long jarg1, OCResource jarg1_, double jarg2, double jarg3, double jarg4);
  public final static native void resourceTagFunctionDescription(long jarg1, OCResource jarg1_, int jarg2);
  public final static native void processBaselineInterface(long jarg1, OCResource jarg1_);
  public final static native long newCollection__SWIG_1(String jarg1, String jarg2, short jarg3, long jarg4);
  public final static native void deleteCollection(long jarg1, OCResource jarg1_);
  public final static native long newLink(long jarg1, OCResource jarg1_);
  public final static native void deleteLink(long jarg1, OCLink jarg1_);
  public final static native void linkAddRelation(long jarg1, OCLink jarg1_, String jarg2);
  public final static native void linkAddLinkParameter(long jarg1, OCLink jarg1_, String jarg2, String jarg3);
  public final static native void collectionAddLink(long jarg1, OCResource jarg1_, long jarg2, OCLink jarg2_);
  public final static native void collectionRemoveLink(long jarg1, OCResource jarg1_, long jarg2, OCLink jarg2_);
  public final static native long collectionGetLinks(long jarg1, OCResource jarg1_);
  public final static native void addCollection(long jarg1, OCResource jarg1_);
  public final static native long collectionGetCollections();
  public final static native boolean collectionAddSupportedResourceType(long jarg1, OCResource jarg1_, String jarg2);
  public final static native boolean collectionAddMandatoryResourceType(long jarg1, OCResource jarg1_, String jarg2);
  public final static native void resourceSetDiscoverable(long jarg1, OCResource jarg1_, boolean jarg2);
  public final static native void resourceSetObservable(long jarg1, OCResource jarg1_, boolean jarg2);
  public final static native void resourceSetPeriodicObservable(long jarg1, OCResource jarg1_, int jarg2);
  public final static native void oc_resource_set_secure_mcast(long jarg1, OCResource jarg1_, boolean jarg2);
  public final static native boolean addResource(long jarg1, OCResource jarg1_);
  public final static native void oc_delayed_delete_resource(long jarg1, OCResource jarg1_);
  public final static native void setConWriteHandler(OCConWriteHandler jarg1);
  public final static native void sendResponse(long jarg1, OCRequest jarg1_, int jarg2);
  public final static native boolean oc_get_request_payload_raw(long jarg1, OCRequest jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native void oc_send_response_raw(long jarg1, OCRequest jarg1_, long jarg2, long jarg3, int jarg4, int jarg5);
  public final static native boolean oc_get_response_payload_raw(long jarg1, OCClientResponse jarg1_, long jarg2, long jarg3, long jarg4);
  public final static native void oc_send_diagnostic_message(long jarg1, OCRequest jarg1_, String jarg2, long jarg3, int jarg4);
  public final static native boolean oc_get_diagnostic_message(long jarg1, OCClientResponse jarg1_, long jarg2, long jarg3);
  public final static native void ignoreRequest(long jarg1, OCRequest jarg1_);
  public final static native void indicateSeparateResponse(long jarg1, OCRequest jarg1_, long jarg2, OCSeparateResponse jarg2_);
  public final static native void setSeparateResponseBuffer(long jarg1, OCSeparateResponse jarg1_);
  public final static native void sendSeparateResponse(long jarg1, OCSeparateResponse jarg1_, int jarg2);
  public final static native int notifyObservers(long jarg1, OCResource jarg1_);
  public final static native boolean oc_init_multicast_update(String jarg1, String jarg2);
  public final static native boolean oc_do_multicast_update();
  public final static native void closeSession(long jarg1, OCEndpoint jarg1_);
  public final static native void OCRole_next_set(long jarg1, OCRole jarg1_, long jarg2, OCRole jarg2_);
  public final static native long OCRole_next_get(long jarg1, OCRole jarg1_);
  public final static native String OCRole_role_get(long jarg1, OCRole jarg1_);
  public final static native String OCRole_authority_get(long jarg1, OCRole jarg1_);
  public final static native void setImmutableDeviceIdentifier(long jarg1, long jarg2, OCUuid jarg2_);
  public final static native void OCClientResponse_payload_set(long jarg1, OCClientResponse jarg1_, long jarg2, OCRepresentation jarg2_);
  public final static native long OCClientResponse_payload_get(long jarg1, OCClientResponse jarg1_);
  public final static native void OCClientResponse__payload_set(long jarg1, OCClientResponse jarg1_, long jarg2);
  public final static native long OCClientResponse__payload_get(long jarg1, OCClientResponse jarg1_);
  public final static native void OCClientResponse__payload_len_set(long jarg1, OCClientResponse jarg1_, long jarg2);
  public final static native long OCClientResponse__payload_len_get(long jarg1, OCClientResponse jarg1_);
  public final static native void OCClientResponse_endpoint_set(long jarg1, OCClientResponse jarg1_, long jarg2, OCEndpoint jarg2_);
  public final static native long OCClientResponse_endpoint_get(long jarg1, OCClientResponse jarg1_);
  public final static native void OCClientResponse_content_format_set(long jarg1, OCClientResponse jarg1_, int jarg2);
  public final static native int OCClientResponse_content_format_get(long jarg1, OCClientResponse jarg1_);
  public final static native void OCClientResponse_code_set(long jarg1, OCClientResponse jarg1_, int jarg2);
  public final static native int OCClientResponse_code_get(long jarg1, OCClientResponse jarg1_);
  public final static native void OCClientResponse_observe_option_set(long jarg1, OCClientResponse jarg1_, int jarg2);
  public final static native int OCClientResponse_observe_option_get(long jarg1, OCClientResponse jarg1_);
  public final static native long new_OCClientResponse();
  public final static native void delete_OCClientResponse(long jarg1);
  public final static native void OCClientCallback_next_set(long jarg1, OCClientCallback jarg1_, long jarg2, OCClientCallback jarg2_);
  public final static native long OCClientCallback_next_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_uri_set(long jarg1, OCClientCallback jarg1_, String jarg2);
  public final static native String OCClientCallback_uri_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_query_set(long jarg1, OCClientCallback jarg1_, String jarg2);
  public final static native String OCClientCallback_query_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_endpoint_set(long jarg1, OCClientCallback jarg1_, long jarg2, OCEndpoint jarg2_);
  public final static native long OCClientCallback_endpoint_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_observeSeq_set(long jarg1, OCClientCallback jarg1_, int jarg2);
  public final static native int OCClientCallback_observeSeq_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_timestamp_set(long jarg1, OCClientCallback jarg1_, long jarg2);
  public final static native long OCClientCallback_timestamp_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_qos_set(long jarg1, OCClientCallback jarg1_, int jarg2);
  public final static native int OCClientCallback_qos_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_method_set(long jarg1, OCClientCallback jarg1_, int jarg2);
  public final static native int OCClientCallback_method_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_mid_set(long jarg1, OCClientCallback jarg1_, int jarg2);
  public final static native int OCClientCallback_mid_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_token_set(long jarg1, OCClientCallback jarg1_, short[] jarg2);
  public final static native short[] OCClientCallback_token_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_tokenLen_set(long jarg1, OCClientCallback jarg1_, short jarg2);
  public final static native short OCClientCallback_tokenLen_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_discovery_set(long jarg1, OCClientCallback jarg1_, boolean jarg2);
  public final static native boolean OCClientCallback_discovery_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_multicast_set(long jarg1, OCClientCallback jarg1_, boolean jarg2);
  public final static native boolean OCClientCallback_multicast_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_stopMulticastReceive_set(long jarg1, OCClientCallback jarg1_, boolean jarg2);
  public final static native boolean OCClientCallback_stopMulticastReceive_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_refCount_set(long jarg1, OCClientCallback jarg1_, short jarg2);
  public final static native short OCClientCallback_refCount_get(long jarg1, OCClientCallback jarg1_);
  public final static native void OCClientCallback_separate_set(long jarg1, OCClientCallback jarg1_, short jarg2);
  public final static native short OCClientCallback_separate_get(long jarg1, OCClientCallback jarg1_);
  public final static native long new_OCClientCallback();
  public final static native void delete_OCClientCallback(long jarg1);
}
