/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCPkiJNI {

  static {
    try {
        System.loadLibrary("iotivity-lite-jni");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native int addMfgCert(long jarg1, byte[] jarg2, byte[] jarg4);
  public final static native int addMfgIntermediateCert(long jarg1, int jarg2, byte[] jarg3);
  public final static native int addMfgTrustAnchor(long jarg1, byte[] jarg2);
  public final static native int addTrustAnchor(long jarg1, byte[] jarg2);
  public final static native void setSecurityProfile(long jarg1, int jarg2, int jarg3, int jarg4);
}
