/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCPki {
  public static int addMfgCert(long device, byte[] cert, byte[] key) {
    return OCPkiJNI.addMfgCert(device, cert, key);
  }

  public static int addMfgIntermediateCert(long device, int credid, byte[] cert) {
    return OCPkiJNI.addMfgIntermediateCert(device, credid, cert);
  }

  public static int addMfgTrustAnchor(long device, byte[] cert) {
    return OCPkiJNI.addMfgTrustAnchor(device, cert);
  }

  public static int addTrustAnchor(long device, byte[] cert) {
    return OCPkiJNI.addTrustAnchor(device, cert);
  }

  public static void setSecurityProfile(long device, int supported_profiles, int current_profile, int mfg_credid) {
    OCPkiJNI.setSecurityProfile(device, supported_profiles, current_profile, mfg_credid);
  }

}
