/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCPlatformInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCPlatformInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCPlatformInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCCoreResJNI.delete_OCPlatformInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setPi(OCUuid value) {
    OCCoreResJNI.OCPlatformInfo_pi_set(swigCPtr, this, OCUuid.getCPtr(value), value);
  }

  public OCUuid getPi() {
    long cPtr = OCCoreResJNI.OCPlatformInfo_pi_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCUuid(cPtr, false);
  }

  public void setMfg_name(String value) {
    OCCoreResJNI.OCPlatformInfo_mfg_name_set(swigCPtr, this, value);
  }

  public String getMfg_name() {
    return OCCoreResJNI.OCPlatformInfo_mfg_name_get(swigCPtr, this);
  }

  public OCPlatformInfo() {
    this(OCCoreResJNI.new_OCPlatformInfo(), true);
  }

}
