/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCRandom {
  public static void init() {
    OCRandomJNI.init();
  }

  public static long randomValue() {
    return OCRandomJNI.randomValue();
  }

  public static void destroy() {
    OCRandomJNI.destroy();
  }

}
