/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCRequest {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCRequest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCMainJNI.delete_OCRequest(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setOrigin(OCEndpoint value) {
    OCMainJNI.OCRequest_origin_set(swigCPtr, this, OCEndpoint.getCPtr(value), value);
  }

  public OCEndpoint getOrigin() {
    long cPtr = OCMainJNI.OCRequest_origin_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCEndpoint(cPtr, false);
  }

  public void setResource(OCResource value) {
    OCMainJNI.OCRequest_resource_set(swigCPtr, this, OCResource.getCPtr(value), value);
  }

  public OCResource getResource() {
    long cPtr = OCMainJNI.OCRequest_resource_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCResource(cPtr, false);
  }

  public String getQuery() {
    return OCMainJNI.OCRequest_query_get(swigCPtr, this);
  }

  public void setQueryLen(long value) {
    OCMainJNI.OCRequest_queryLen_set(swigCPtr, this, value);
  }

  public long getQueryLen() {
    return OCMainJNI.OCRequest_queryLen_get(swigCPtr, this);
  }

  public void setRequestPayload(OCRepresentation value) {
    OCMainJNI.OCRequest_requestPayload_set(swigCPtr, this, OCRepresentation.getCPtr(value), value);
  }

  public OCRepresentation getRequestPayload() {
    long cPtr = OCMainJNI.OCRequest_requestPayload_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCRepresentation(cPtr, false);
  }

  public void set_payload(SWIGTYPE_p_unsigned_char value) {
    OCMainJNI.OCRequest__payload_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char get_payload() {
    long cPtr = OCMainJNI.OCRequest__payload_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void set_payload_len(long value) {
    OCMainJNI.OCRequest__payload_len_set(swigCPtr, this, value);
  }

  public long get_payload_len() {
    return OCMainJNI.OCRequest__payload_len_get(swigCPtr, this);
  }

  public void setContent_format(oc_content_format_t value) {
    OCMainJNI.OCRequest_content_format_set(swigCPtr, this, value.swigValue());
  }

  public oc_content_format_t getContent_format() {
    return oc_content_format_t.swigToEnum(OCMainJNI.OCRequest_content_format_get(swigCPtr, this));
  }

  public void setResponse(OCResponse value) {
    OCMainJNI.OCRequest_response_set(swigCPtr, this, OCResponse.getCPtr(value), value);
  }

  public OCResponse getResponse() {
    long cPtr = OCMainJNI.OCRequest_response_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCResponse(cPtr, false);
  }

  public OCRequest() {
    this(OCMainJNI.new_OCRequest(), true);
  }

}
