/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCResourceType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCResourceType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCResourceType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCCollectionUtilJNI.delete_OCResourceType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setNext(OCResourceType value) {
    OCCollectionUtilJNI.OCResourceType_next_set(swigCPtr, this, OCResourceType.getCPtr(value), value);
  }

  public OCResourceType getNext() {
    long cPtr = OCCollectionUtilJNI.OCResourceType_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCResourceType(cPtr, false);
  }

  public void setRt(String value) {
    OCCollectionUtilJNI.OCResourceType_rt_set(swigCPtr, this, value);
  }

  public String getRt() {
    return OCCollectionUtilJNI.OCResourceType_rt_get(swigCPtr, this);
  }

  public OCResourceType() {
    this(OCCollectionUtilJNI.new_OCResourceType(), true);
  }

}
