/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCRepJNI {

  static {
    try {
        System.loadLibrary("iotivity-lite-jni");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native long new_CborEncoder();
  public final static native void delete_CborEncoder(long jarg1);
  public final static native void deleteBuffer();
  public final static native void newBuffer(int jarg1);
  public final static native void setDouble(long jarg1, CborEncoder jarg1_, String jarg2, double jarg3);
  public final static native void setLong(long jarg1, CborEncoder jarg1_, String jarg2, long jarg3);
  public final static native void setUnsignedInt(long jarg1, CborEncoder jarg1_, String jarg2, long jarg3);
  public final static native void setBoolean(long jarg1, CborEncoder jarg1_, String jarg2, boolean jarg3);
  public final static native void setTextString(long jarg1, CborEncoder jarg1_, String jarg2, String jarg3);
  public final static native void setByteString(long jarg1, CborEncoder jarg1_, String jarg2, byte[] jarg3);
  public final static native long beginArray(long jarg1, CborEncoder jarg1_);
  public final static native void endArray(long jarg1, CborEncoder jarg1_, long jarg2, CborEncoder jarg2_);
  public final static native long beginLinksArray();
  public final static native void endLinksArray();
  public final static native long beginRootObject();
  public final static native void endRootObject();
  public final static native void addByteString(long jarg1, CborEncoder jarg1_, byte[] jarg2);
  public final static native void addTextString(long jarg1, CborEncoder jarg1_, String jarg2);
  public final static native void addDouble(long jarg1, CborEncoder jarg1_, double jarg2);
  public final static native void addLong(long jarg1, CborEncoder jarg1_, long jarg2);
  public final static native void addBoolean(long jarg1, CborEncoder jarg1_, boolean jarg2);
  public final static native void setKey(long jarg1, CborEncoder jarg1_, String jarg2);
  public final static native long openArray(long jarg1, CborEncoder jarg1_, String jarg2);
  public final static native void closeArray(long jarg1, CborEncoder jarg1_, long jarg2, CborEncoder jarg2_);
  public final static native long beginObject(long jarg1, CborEncoder jarg1_);
  public final static native void endObject(long jarg1, CborEncoder jarg1_, long jarg2, CborEncoder jarg2_);
  public final static native long objectArrayBeginItem(long jarg1, CborEncoder jarg1_);
  public final static native void objectArrayEndItem(long jarg1, CborEncoder jarg1_, long jarg2, CborEncoder jarg2_);
  public final static native long openObject(long jarg1, CborEncoder jarg1_, String jarg2);
  public final static native void closeObject(long jarg1, CborEncoder jarg1_, long jarg2, CborEncoder jarg2_);
  public final static native void setLongArray(long jarg1, CborEncoder jarg1_, String jarg2, long[] jarg3);
  public final static native void setBooleanArray(long jarg1, CborEncoder jarg1_, String jarg2, boolean[] jarg3);
  public final static native void setDoubleArray(long jarg1, CborEncoder jarg1_, String jarg2, double[] jarg3);
  public final static native void setStringArray(long jarg1, CborEncoder jarg1_, String jarg2, String[] jarg3);
  public final static native long getOCRepresentaionFromRootObject();
  public final static native int getCborErrno();
  public final static native void clearCborErrno();
  public final static native Long getLong(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native Boolean getBoolean(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native Double getDouble(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native byte[] getByteString(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native String getString(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native long[] getLongArray(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native boolean[] getBooleanArray(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native double[] getDoubleArray(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native byte[][] getByteStringArray(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native String[] getStringArray(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native long getObject(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native long getObjectArray(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native long new_OCArray();
  public final static native void delete_OCArray(long jarg1);
  public final static native long[] ocArrayToLongArray(long jarg1, OCArray jarg1_);
  public final static native boolean[] ocArrayToBooleanArray(long jarg1, OCArray jarg1_);
  public final static native double[] ocArrayToDoubleArray(long jarg1, OCArray jarg1_);
  public final static native String[] ocArrayToStringArray(long jarg1, OCArray jarg1_);
  public final static native String toJSON(long jarg1, OCRepresentation jarg1_, boolean jarg2);
  public final static native void oc_rep_encode_raw(long jarg1, long jarg2);
  public final static native void OCRepresentation_value_set(long jarg1, OCRepresentation jarg1_, long jarg2, OCValue jarg2_);
  public final static native long OCRepresentation_value_get(long jarg1, OCRepresentation jarg1_);
  public final static native void OCRepresentation_type_set(long jarg1, OCRepresentation jarg1_, int jarg2);
  public final static native int OCRepresentation_type_get(long jarg1, OCRepresentation jarg1_);
  public final static native void OCRepresentation_next_set(long jarg1, OCRepresentation jarg1_, long jarg2, OCRepresentation jarg2_);
  public final static native long OCRepresentation_next_get(long jarg1, OCRepresentation jarg1_);
  public final static native void OCRepresentation_name_set(long jarg1, OCRepresentation jarg1_, String jarg2);
  public final static native String OCRepresentation_name_get(long jarg1, OCRepresentation jarg1_);
  public final static native long new_OCRepresentation();
  public final static native void delete_OCRepresentation(long jarg1);
  public final static native void OCValue_integer_set(long jarg1, OCValue jarg1_, long jarg2);
  public final static native long OCValue_integer_get(long jarg1, OCValue jarg1_);
  public final static native void OCValue_Bool_set(long jarg1, OCValue jarg1_, boolean jarg2);
  public final static native boolean OCValue_Bool_get(long jarg1, OCValue jarg1_);
  public final static native void OCValue_Double_set(long jarg1, OCValue jarg1_, double jarg2);
  public final static native double OCValue_Double_get(long jarg1, OCValue jarg1_);
  public final static native void OCValue_string_set(long jarg1, OCValue jarg1_, String jarg2);
  public final static native String OCValue_string_get(long jarg1, OCValue jarg1_);
  public final static native void OCValue_array_set(long jarg1, OCValue jarg1_, long jarg2, OCArray jarg2_);
  public final static native long OCValue_array_get(long jarg1, OCValue jarg1_);
  public final static native void OCValue_object_set(long jarg1, OCValue jarg1_, long jarg2, OCRepresentation jarg2_);
  public final static native long OCValue_object_get(long jarg1, OCValue jarg1_);
  public final static native void OCValue_objectArray_set(long jarg1, OCValue jarg1_, long jarg2, OCRepresentation jarg2_);
  public final static native long OCValue_objectArray_get(long jarg1, OCValue jarg1_);
  public final static native long new_OCValue();
  public final static native void delete_OCValue(long jarg1);
}
