/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCResource {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCResource(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCResource obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCMainJNI.delete_OCResource(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OCResource getNext() {
    long cPtr = OCMainJNI.OCResource_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCResource(cPtr, false);
  }

  public long getDevice() {
    return OCMainJNI.OCResource_device_get(swigCPtr, this);
  }

  public String getName() {
    return OCMainJNI.OCResource_name_get(swigCPtr, this);
  }

  public String getUri() {
    return OCMainJNI.OCResource_uri_get(swigCPtr, this);
  }

  public String[] getTypes() {
    return OCMainJNI.OCResource_types_get(swigCPtr, this);
}

  public int getInterfaces() { return OCMainJNI.OCResource_interfaces_get(swigCPtr, this); }

  public int getDefaultInterface() { return OCMainJNI.OCResource_defaultInterface_get(swigCPtr, this); }

  public int getProperties() { return OCMainJNI.OCResource_properties_get(swigCPtr, this); }

  public double[] getTagPositionRelative() {
    return OCMainJNI.OCResource_tagPositionRelative_get(swigCPtr, this);
  }

  public OCPositionDescription getTagPositionDescription() {
    return OCPositionDescription.swigToEnum(OCMainJNI.OCResource_tagPositionDescription_get(swigCPtr, this));
  }

  public OCEnum getTagFunctionDescription() {
    return OCEnum.swigToEnum(OCMainJNI.OCResource_tagFunctionDescription_get(swigCPtr, this));
  }

  public short getNumObservers() {
    return OCMainJNI.OCResource_numObservers_get(swigCPtr, this);
  }

  public int getObservePeriodSeconds() {
    return OCMainJNI.OCResource_observePeriodSeconds_get(swigCPtr, this);
  }

  public OCResource() {
    this(OCMainJNI.new_OCResource(), true);
  }

}
