/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCRepresentation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCRepresentation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCRepresentation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCRepJNI.delete_OCRepresentation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setValue(OCValue value) {
    OCRepJNI.OCRepresentation_value_set(swigCPtr, this, OCValue.getCPtr(value), value);
  }

  public OCValue getValue() {
    long cPtr = OCRepJNI.OCRepresentation_value_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCValue(cPtr, false);
  }

  public void setType(OCType value) {
    OCRepJNI.OCRepresentation_type_set(swigCPtr, this, value.swigValue());
  }

  public OCType getType() {
    return OCType.swigToEnum(OCRepJNI.OCRepresentation_type_get(swigCPtr, this));
  }

  public void setNext(OCRepresentation value) {
    OCRepJNI.OCRepresentation_next_set(swigCPtr, this, OCRepresentation.getCPtr(value), value);
  }

  public OCRepresentation getNext() {
    long cPtr = OCRepJNI.OCRepresentation_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCRepresentation(cPtr, false);
  }

  public void setName(String value) {
    OCRepJNI.OCRepresentation_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return OCRepJNI.OCRepresentation_name_get(swigCPtr, this);
  }

  public OCRepresentation() {
    this(OCRepJNI.new_OCRepresentation(), true);
  }

}
