/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCResponseBuffer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCResponseBuffer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCResponseBuffer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCMainJNI.delete_OCResponseBuffer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setResponseLength(long value) {
    OCMainJNI.OCResponseBuffer_responseLength_set(swigCPtr, this, value);
  }

  public long getResponseLength() {
    return OCMainJNI.OCResponseBuffer_responseLength_get(swigCPtr, this);
  }

  public void setCode(int value) {
    OCMainJNI.OCResponseBuffer_code_set(swigCPtr, this, value);
  }

  public int getCode() {
    return OCMainJNI.OCResponseBuffer_code_get(swigCPtr, this);
  }

  public OCResponseBuffer() {
    this(OCMainJNI.new_OCResponseBuffer(), true);
  }

}
