/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCRole {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCRole(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCRole obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public void setNext(OCRole value) {
    OCMainJNI.OCRole_next_set(swigCPtr, this, OCRole.getCPtr(value), value);
  }

  public OCRole getNext() {
    long cPtr = OCMainJNI.OCRole_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCRole(cPtr, false);
  }

  public String getRole() {
    return OCMainJNI.OCRole_role_get(swigCPtr, this);
  }

  public String getAuthority() {
    return OCMainJNI.OCRole_authority_get(swigCPtr, this);
  }

}
