/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCSessionEvents {
  public static void startEvent(OCEndpoint endpoint) {
    OCSessionEventsJNI.startEvent(OCEndpoint.getCPtr(endpoint), endpoint);
  }

  public static void endEvent(OCEndpoint endpoint) {
    OCSessionEventsJNI.endEvent(OCEndpoint.getCPtr(endpoint), endpoint);
  }

  public static void setEventDelay(int secs) {
    OCSessionEventsJNI.setEventDelay(secs);
  }

}
