/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public enum OCSessionState {
  OC_SESSION_CONNECTED,
  OC_SESSION_DISCONNECTED;

  public final int swigValue() {
    return swigValue;
  }

  public static OCSessionState swigToEnum(int swigValue) {
    OCSessionState[] swigValues = OCSessionState.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (OCSessionState swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + OCSessionState.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private OCSessionState() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private OCSessionState(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private OCSessionState(OCSessionState swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

