/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCSecurityAce {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCSecurityAce(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCSecurityAce obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public void setNext(OCSecurityAce value) {
    OCObtJNI.OCSecurityAce_next_set(swigCPtr, this, OCSecurityAce.getCPtr(value), value);
  }

  public OCSecurityAce getNext() {
    long cPtr = OCObtJNI.OCSecurityAce_next_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCSecurityAce(cPtr, false);
  }

  public void setSubjectType(OCAceSubjectType value) {
    OCObtJNI.OCSecurityAce_subjectType_set(swigCPtr, this, value.swigValue());
  }

  public OCAceSubjectType getSubjectType() {
    return OCAceSubjectType.swigToEnum(OCObtJNI.OCSecurityAce_subjectType_get(swigCPtr, this));
  }

  public void setSubject(OCAceSubject value) {
    OCObtJNI.OCSecurityAce_subject_set(swigCPtr, this, OCAceSubject.getCPtr(value), value);
  }

  public OCAceSubject getSubject() {
    long cPtr = OCObtJNI.OCSecurityAce_subject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCAceSubject(cPtr, false);
  }

  public void setAceid(int value) {
    OCObtJNI.OCSecurityAce_aceid_set(swigCPtr, this, value);
  }

  public int getAceid() {
    return OCObtJNI.OCSecurityAce_aceid_get(swigCPtr, this);
  }

  public void setPermission(int value) {
    OCObtJNI.OCSecurityAce_permission_set(swigCPtr, this, value);
  }

  public int getPermission() { return OCObtJNI.OCSecurityAce_permission_get(swigCPtr, this); }

  public OCAceResource getResourcesListHead() {
    long cPtr = OCObtJNI.OCSecurityAce_getResourcesListHead(swigCPtr, this);
    return (cPtr == 0) ? null : new OCAceResource(cPtr, false);
  }

}
