/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCSoftwareUpdate {
  public static void notifyNewVersionAvailable(long device, String version, OCSoftwareUpdateResult result) {
    OCSoftwareUpdateJNI.notifyNewVersionAvailable(device, version, result.swigValue());
  }

  public static void notifyDownload(long device, String version, OCSoftwareUpdateResult result) {
    OCSoftwareUpdateJNI.notifyDownload(device, version, result.swigValue());
  }

  public static void notifyUpgrading(long device, String version, long timestamp, OCSoftwareUpdateResult result) {
    OCSoftwareUpdateJNI.notifyUpgrading(device, version, timestamp, result.swigValue());
  }

  public static void notifyDone(long device, OCSoftwareUpdateResult result) {
    OCSoftwareUpdateJNI.notifyDone(device, result.swigValue());
  }

  public static void setImpl(OCSoftwareUpdateHandler swupdateImpl) {
    OCSoftwareUpdateJNI.setImpl(swupdateImpl);
  }

}
