/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCUuidUtil implements OCUuidUtilConstants {
  public static OCUuid stringToUuid(String str) {
    long cPtr = OCUuidUtilJNI.stringToUuid(str);
    return (cPtr == 0) ? null : new OCUuid(cPtr, true);
  }

  public static String uuidToString(OCUuid uuid) {
    return OCUuidUtilJNI.uuidToString(OCUuid.getCPtr(uuid), uuid);
  }

  public static OCUuid generateUuid() {
    long cPtr = OCUuidUtilJNI.generateUuid();
    return (cPtr == 0) ? null : new OCUuid(cPtr, true);
  }

}
