/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public interface OCUuidUtilConstants {
  public final static int OC_UUID_LEN = OCUuidUtilJNI.OC_UUID_LEN_get();
}
