/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.iotivity;

public class OCValue {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OCValue(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OCValue obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        OCRepJNI.delete_OCValue(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setInteger(long value) {
    OCRepJNI.OCValue_integer_set(swigCPtr, this, value);
  }

  public long getInteger() {
    return OCRepJNI.OCValue_integer_get(swigCPtr, this);
  }

  public void setBool(boolean value) {
    OCRepJNI.OCValue_Bool_set(swigCPtr, this, value);
  }

  public boolean getBool() {
    return OCRepJNI.OCValue_Bool_get(swigCPtr, this);
  }

  public void setDouble(double value) {
    OCRepJNI.OCValue_Double_set(swigCPtr, this, value);
  }

  public double getDouble() {
    return OCRepJNI.OCValue_Double_get(swigCPtr, this);
  }

  public void setString(String value) {
    OCRepJNI.OCValue_string_set(swigCPtr, this, value);
  }

  public String getString() {
    return OCRepJNI.OCValue_string_get(swigCPtr, this);
  }

  public void setArray(OCArray value) {
    OCRepJNI.OCValue_array_set(swigCPtr, this, OCArray.getCPtr(value), value);
  }

  public OCArray getArray() {
    long cPtr = OCRepJNI.OCValue_array_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCArray(cPtr, false);
  }

  public void setObject(OCRepresentation value) {
    OCRepJNI.OCValue_object_set(swigCPtr, this, OCRepresentation.getCPtr(value), value);
  }

  public OCRepresentation getObject() {
    long cPtr = OCRepJNI.OCValue_object_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCRepresentation(cPtr, false);
  }

  public void setObjectArray(OCRepresentation value) {
    OCRepJNI.OCValue_objectArray_set(swigCPtr, this, OCRepresentation.getCPtr(value), value);
  }

  public OCRepresentation getObjectArray() {
    long cPtr = OCRepJNI.OCValue_objectArray_get(swigCPtr, this);
    return (cPtr == 0) ? null : new OCRepresentation(cPtr, false);
  }

  public OCValue() {
    this(OCRepJNI.new_OCValue(), true);
  }

}
